[build]
builder = "nixpacks"
buildCommand = "rm -rf .next && npm run build"

[deploy]
startCommand = "npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
healthcheckPath = "/api/ping"
healthcheckTimeout = 100
