[build]
builder = "nixpacks"
buildCommand = "npm install && npm run build"

[deploy]
startCommand = "npm run start"
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 10

[healthcheck]
path = "/api/health"
timeout = 100
interval = 60

[[services]]
name = "introalignment-web"
